default: &default
  issuer: redmine
development:
  <<: *default
  base_domain: http://localhost:3000
  idp_domain: https://mars.pipi
production:
  <<: *default
  base_domain: https://3coms.org
  idp_domain: https://id.pipihosting.com
